### ISSUE TITLE
Update augs -> xrpk's

### ISSUE THREAD

**Issue by avaer** [webaverse/docs#11]
Some of the pages use the "augs" term, but in an effort to reduce friction, let's just call them "XR Packages" or "XRPKs" for now.

**Comment by Zetaphor** [comment]
Pages that contain `aug`

* index.md
* about.md
* creating-an-aug.md
* distributing-xrpackage.md
* getting-started.md
* metachromium-overview.md

A couple of these are just links back to `creating-an-aug.md`

**Comment by avaer** [comment]
I think Webaverse.com was the only thing that had augs, and it's been replaced.
