### ISSUE TITLE
Questions to answer

### ISSUE THREAD

**Issue by avaer** [webaverse/docs#5]
Here is a list of questions I think would be good to answer in the docs.

Some of these might seem misguided -- but they are questions that have been asked and it's our job to make the answers clear. I wouldn't advocate a FAQ format since that can be overwhelming, but it can be used as a shape for the direction of the docs/some terminology to use.

- What is a "package"?
- How do I download the Webaverse SDK?
- What headsets does it work on?
- How do I use Webaverse in my A-Frame app?
- Do you have an example I can follow for A-Frame?
- How do I run my own server?
- How do I set my avatar?
- How do I make a scene?
- How do I load my sword in hubs?

#### Example

An example of a good direction might be

> What is a "package"?

Packages are virtual things you drop into a 3D world. Here's a video of how it works. Go to [XRPackage sample world link] and try it out.

Technically speaking, packages are a special file called a web bundle. To learn how to create you own packages, here is a tutorial on Glitch: [Glitch Link] Or if you want to just convert a file to a package, you can do it here: [XRPackage Inspect link]

etc.

**Comment by shu8** [comment]
Just a note to keep track of what's been answered so far:

- [x] What is a "package"?
- [x] How do I download the Webaverse SDK?
- [x] What headsets does it work on?
- [x] How do I use Webaverse in my A-Frame app?
- [ ] Do you have an example I can follow for A-Frame?
- [x] How do I run my own server?
- [ ] How do I set my avatar?
- [x] How do I make a scene?
- [ ] How do I load my sword in hubs?

**Comment by avaer** [comment]
Thanks! Note that some of these, like `How do I set my avatar?` are asked but do not have a good UX answer yet :)

**Comment by shu8** [comment]
Thanks @avaer, I think these should all be answered somewhere in the docs after https://github.com/webaverse/docs/pull/17.

Except for `How do I load my sword in hubs?`, which I'm a bit unsure about myself! I think this would be the webaverse fork of hubs (https://github.com/webaverse/hubs) but I'm not sure how we load XRPKs in it

**Comment by avaer** [comment]
> Except for How do I load my sword in hubs?, which I'm a bit unsure about myself!

The answer is probably to add a Hubs package to the world, which would need to be loaded simultaneously with the sword.

The more general question being asked here, however, is how multiplayer works. The answer to that is the packages do their own multiplayer via the APIs exposed to the application. Which leads to the question of what are the APIs exposed to the application (via `XRPackage`, `XRPackageEngine`, and the `xrpackage` global in the `iframe` which runs the packages); these need to be documented.

**Comment by avaer** [comment]
Here are some more questions that came up during PR review (they don't need to be addressed in that PR, just logging them here for future work):

- How are packages loaded, technically speaking? (answer: via `iframes`, with content loaded from the page's Service Worker)
- What is the API for `XRPackage`?
- What is the API for `XRPackageEngine`?
- What is the API for `xrpackage`? (this is the API exposed to iframes that are running packages)
- What is the API for GLTF worker scripts? (this is the `script` property of the `manifest.json`)
- What is the API for grabbing/wearing objects on an avatar? (this is specified in the `manifest.json`)
- How do I get a Blender model into Webaverse? (answer: export as GLTF)
- How do I get a VRoid Studio avatar into Webaverse? (answer: export as VRM, will need screenshots)
- How do I compile my Unity app for Webaverse? (answer: use the exporter to get a `.wbn`)
- How do I use multiplayer? (answer: add a Hubs or multiplayer package to the world e.g. https://github.com/webaverse/multiplayer, or something else possible Networked A-Frame (NAF) or MetaRTC-based)

**Comment by shu8** [comment]
> What is the API for GLTF worker scripts? (this is the script property of the manifest.json)

I couldn't seem to find this references in `xrpackage.js` -- is there an example or implementation I could look at to document this?

**Comment by avaer** [comment]
Yes, I believe there is a basic script load here: https://github.com/webaverse/xrpackage-site/blob/378d1c6df4c4697918aa821c189bef995dd88e28/examples/gltf/model.js#L4

**Comment by shu8** [comment]
Thanks! Added that to #29 :)
